version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_api
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - .:/nodejs_api_template
      - /nodejs_api_template/node_modules
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ddl/api_template_db.sql:/docker-entrypoint-initdb.d/api_template_db.sql
    restart: always

volumes:
  db_data:
